# name: ðŸš€ Deploy Laravel App

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     name: ðŸ§³ Deploy to Server
#     runs-on: ubuntu-latest

#     steps:
#       - name: â¬ Checkout Code
#         uses: actions/checkout@v3

#       - name: ðŸ” Setup SSH
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa
#           echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

#       - name: ðŸš€ Deploy via SSH
#         run: |
#           ssh root@185.191.141.44 << 'EOF'
#             cd /var/www/Useful-contents-library/
#             git pull origin main
#             docker exec abduvoris-content-hub-app composer install --no-interaction --prefer-dist --optimize-autoloader
#             docker exec abduvoris-content-hub-app php artisan config:clear
#             docker exec abduvoris-content-hub-app php artisan route:clear
#             docker exec abduvoris-content-hub-app php artisan view:clear
#             docker exec abduvoris-content-hub-app php artisan cache:clear
#             docker exec abduvoris-content-hub-app php artisan config:cache
#             docker exec abduvoris-content-hub-app php artisan optimize
#             docker exec abduvoris-content-hub-app php artisan migrate --force
#           EOF
